server:
  port: 8080

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/mapper/*.


spring:
  datasource:
    # 配置数据源
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    url:
    username:
    password:
  redis:
    cluster:
      nodes:
      max-redirects: 3
    timeout: 2000
    password: 12345678
  data:
    elasticsearch:
      cluster-nodes:
      cluster-name: my-application
      repositories:
        enabled: true


dubbo:
  application:
    name: learn-for-forever
    qos-enable: true
    qos-port: 23323
    qos-accept-foreign-ip: true
  protocol:
    name: dubbo
  registry:
    port: 55555
    address:
  provider:
    version: 1.0.0
  consumer:
    check: false
    version: 1.0.0

rocketmq:
  namesrvAddr:
  consumer:
    group: learn-for-forever-consumer-group
  producer:
    group: learn-for-forever-producer-group
    retryTimes: 3
  order:
    consumer:
      topic: topic_order_detail
      tags: tag_order_settle_ready

app:
  id: learn-for-forever
apollo:
  bootstrap:
    enabled: true

zkAddress:
zkPort:

#zookeeperAddress: zk1.bw365.net:2181,zk2.bw365.net:2181,zk3.bw365.net:2181
#
#nameSpace: bw-job
#
#test.value: 22

