package com.learn.forever;

/**
 * Hello world!
 *
 */
public class Constants {
    public static final String UPDATE = "UPDATE";
    public static final String INSERT = "INSERT";
    public static final String BINLOG_ERROR_TAG = "binlog_error";
    public static final String JOB_ERROR_TAG = "job_error";
    public static final String WHERE = "where";
    public static final String KEY_RETRY_NUM = "retryNum";
    public static final String KEY_REQUEST_TIME = "requestTime";
    public static final String KEY_TABLE_NAME = "tableName";
    public static final String KEY_ORDER_NO = "orderNo";
    public static final String KEY_USER_ID = "userId";
    public static final String KEY_UID = "uid";
    public static final String ORDER_BY = " order by id asc";
    public static final String ID_WHERE = " and id > ";
    public static final String DEFAULT_AND = "  1=1 ";
    public static final String KEY_INDEX_NAME = "indexName";
    public static final String KEY_ID = "id";
    public static final String LIMIT = " LIMIT ";
    public static final String KEY_APP_SOURCE_ID = "sourceId";
    public static final String KEY_SHOP_ID = "shopId";
    public static final String KEY_ORDER_ID = "orderId";
    public static final String KEY_ORDER_TYPES = "orderTypes";
    public static final String KEY_GROUP_FLAG = "groupFlag";
    public static final String KEY_STATUS_CODE = "statusCode";
    public static final String KEY_ORDER_REFUND_CODE = "refundStatus";
    public static final String KEY_BUYER_SHOWFLAG = "buyerShowFlag";
    public static final String KEY_SELLER_SHOWFLAG = "sellerShowFlag";
    public static final String KEY_ITEM_PATH = "details";
    public static final String KEY_PERIOD = ".";
    public static final String KEY_ITEM_NAME = "itemName";
    public static final String KEY_NAME = "name";
    public static final String KEY_PAID_TIME_FIELD = "paid_time";
    public static final String KEY_ITEM_NUMBS = "itemNums";
    public static final String KEY_KEYWORD = "keyword";
    public static final String KEY_CREATE_TIME = "createTime";
    public static final String KEY_PAID_TIME = "paidTime";
    public static final String KEY_CONFIRM_TIME = "confirmTime";
    public static final String KEY_BUYER_PHONE = "buyerPhone";
    public static final String KEY_BUYER_ID = "buyerId";
    public static final String KEY_CON_PHONE = "conPhone";
    public static final String SEARCH_RT_SYSTEM = "bw-search-rt";
    public static final String KEY_ORDER_TAG = "orderTag";
    public static final String KEY_LC = "lc";
    public static final String KEY_ORDER_STATUS_CODE = "orderStatusCode";
    public static final String KEY_DELIVERABLE_TIME = "deliverableTime";
    public static final String KEY_SCM_TYPE = "scmType";
    public static final String KEY_SCM_ORDER_NO = "scmOrderNo";
    public static final String KEY_USER_CREATE_TIME = "gmtCreate";
    public static final String KEY_PT = "pt";
    public static final String KEY_AUDIT_STATUS = "status";
    public static final String KEY_DATA_SOURCE = "ds";
    public static final String KEY_IS_AUDIT = "isAud";
    public static final String KEY_SHOW_FLAG = "sf";
    public static final String KEY_ARTICLE_TYPE = "at";
    public static final String KEY_ARTICLE_STYLE = "as";
    public static final String KEY_DSID = "dsid";
    public static final String KEY_LATEST_PAID_TIME = "latestPaidTime";
    public static final String KEY_TERMINAL_TYPE = "terminalType";
    public static final String KEY_REGISTER_SOURCE = "registerSource";
    public static final String KEY_GRD_EMPLOYEE = "grdEmployee";
    public static final String KEY_VIP_FLAG = "vipFlag";
    public static final String KEY_NICKNAME = "nickName";
    public static final String KEY_TITLE = "title";
    public static final String KEY_CONTENT = "content";
    public static final String KEY_MOBILE_PATH = "mobiles";
    public static final String KEY_ITEMS_PATH = "items";
    public static final String KEY_MOBILE = "mobile";
    public static final String KEY_LEVEL_TYPE = "levelType";
    public static final String KEY_PLATFORM_ID = "platformId";
    public static final String KEY_GRD_DELETE = "grdDelete";
    public static final String KEY_COMMENT_CONTENT = "content";
    public static final String KEY_IS_DEL = "isdel";
    public static final String COMMA = ",";
    public static final String KEY_STATUS = "status";
    public static final String KEY_COMMENT_ID = "commentId";
    public static final String KEY_ITEM_ID = "itemId";
    public static final String KEY_DESCRIBE_SCORE = "describeScore";
    public static final String KEY_COMMENT_TYPE = "commentType";
    public static final String KEY_EXAMINE_STATUS = "examineStatus";
    public static final String KEY_GRD_SENSITIVE = "grdSensitive";
    public static final String KEY_IMAGE_URLS = "imageUrls";
    public static final String KEY_GRD_SHOW = "grdShow";
    public static final String KEY_GMT_CREATE = "gmtCreate";
    public static final String KEY_COMMENT_DATE_ID = "commentDataSourceId";
    public static final String KEY_ARTICLE_ID = "articleId";

    public static final String KEY_ADDED_FLAG = "af";
    public static final String KEY_ITEM_AUDIT_STATUS = "as";
    public static final String KEY_BRAND_ID = "bid";
    public static final String KEY_BRAND_NAME = "bname";
    public static final String KEY_BRAND_ENGLISH_NAME = "benname";
    public static final String KEY_CATEGORY_THIRD_ID = "ctid";
    public static final String KEY_CATEGORY_THIRD_NAME = "ctname";
    public static final String KEY_CATEGORY_SECOND_ID = "csid";
    public static final String KEY_CATEGORY_SECOND_NAME = "csname";
    public static final String KEY_CATEGORY_FIRST_ID = "cfid";
    public static final String KEY_CATEGORY_FIRST_NAME = "cfname";
    public static final String KEY_PREFER_PRICE = "pprice";
    public static final String KEY_REDPACKET_PRICERED_PACKET_PRICE = "rprice";
    public static final String KEY_DEFAULT_REDPACKET_RATIO = "drpratio";
    public static final String KEY_REDPACKET_FLAG = "rpsflag";
    public static final String KEY_FICTITIOUS_SALES_COUNT = "fscount";
    public static final String KEY_SHELF_TIME = "stime";
    public static final String KEY_ITEM_SHOP_ID = "sid";
    public static final String KEY_FICTITIOUS_FLAG = "fflag";
    public static final String KEY_ACTIVITY_LIST = "activityList";
    public static final String KEY_ACTIVITY_TYPE_LIST = "atlist";
    public static final String KEY_CPS_SORT = "cpssort";
    public static final String KEY_ESTIMATE_COMMISSION = "cpsamt";
    public static final String KEY_CPS_HIDE_FLAG = "cpshideflag";
    public static final String KEY_ACTIVITY_TYPE = "activityList.type";
    public static final String KEY_ACTIVITY_PRICE = "activityList.price";
    public static final String ORDER_INDEX_NAME = "order_rt_index";
    public static final String COMMENT_INDEX_NAME = "comment_index_rt";
    public static final String REPLY_INDEX_NAME = "reply_index_rt";
    public static final String USER_INDEX_NAME = "user_rt_index";
    public static final String SHOWKER_INDEX_NAME = "showker_rt_index";
    public static final String ARTICLE_INDEX_NAME = "article_rt_index";
    public static final String ITEM_INDEX_NAME = "item_search_index";
    public static final String ORDER_BASIC_TABLE_NAME = "order_basic";
    public static final String ZPT_ORDER_TABLE_NAME = "zpt_order";
    public static final String ZPT_ORDER_SALES_TABLE_NAME = "zpt_order_sales";


    public static final String SCORE = "_score";
    public static final int PAGE = 1;
    public static final int NOT_VIP = 0;
    public static final int AUDITED = 1;
    public static final int MAX_RETRY_NUM = 5;
    public static final int TIME_LIMIT = 10;
    public static final int FIRST_RETRY_NUM = 0;
    public static final int PAGE_SIZE = 20;
    public static final int SEARCH_START = 0;
    public static final int SEARCH_OFFSET = 20;
    public static final int DEFAULT_ORDER_TAG = 0;
    public static final int GLOBLE_ORDER_TAG = 1;
    public static final int ORDER_PAID_4_SHIPPING = 7;
    public static final Integer DELETED = 1;
    public static final Integer SORT_BY_HOT = 1;
    public static final Integer SORT_BY_TIME = 3;

    public static final Integer SORT_BY_SYNTHESIS = 0;
    public static final Integer TASK_SELECT_LIMIT = 1000;
    public static final Integer NOT_DELETE = 0;
    public static final Integer WAIT_AUDIT = 1;
    public static final Integer AUDIT_PASS = 3;
    public static final Integer REFUND_SUCCESS = 13;
    public static final Short ZPT_ORDER_TYPE = 31;
    public static final Integer ZPT_VALID_STATUS = 1;


}
