server:
  port: 8080

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/mapper/*.


spring:
  datasource:
    # 配置数据源
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://mi1.bw365.net:3306/bw_union?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull&amp;useSSL=false&amp;serverTimezone=Asia/Shanghai
    username: rd
    password: bw888888
  redis:
    cluster:
      nodes: 192.168.27.11:8001,192.168.27.11:8002,192.168.27.12:8001,192.168.27.12:8002,192.168.27.13:8001,192.168.27.13:8002
      max-redirects: 3
    timeout: 2000
    password: 12345678

dubbo:
  application:
    name: learn-for-forever
    qos-enable: true
    qos-port: 23323
    qos-accept-foreign-ip: true
  protocol:
    name: dubbo
  registry:
    port: 55555
    address: zookeeper://zk1.bw365.net:2181?backup=zk2.bw365.net:2181,zk3.bw365.net:2181
  provider:
    version: 1.0.0
  consumer:
    check: false
    version: 1.0.0
