server:
  port: 8080

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/mapper/*.


spring:
  datasource:
    # 配置数据源
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://mi1.bw365.net:3306/bw_union?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Bw888888
  redis:
    cluster:
      nodes: 192.168.27.11:8001,192.168.27.11:8002,192.168.27.12:8001,192.168.27.12:8002,192.168.27.13:8001,192.168.27.13:8002
      max-redirects: 3
    timeout: 2000
    password: 12345678
  data:
    elasticsearch:
      cluster-nodes: 47.105.185.162:9200
      cluster-name: my-application
      repositories:
        enabled: true


dubbo:
  application:
    name: learn-for-forever
    qos-enable: true
    qos-port: 23323
    qos-accept-foreign-ip: true
  protocol:
    name: dubbo
  registry:
    port: 55555
    address: zookeeper://zk1.bw365.net:2181?backup=zk2.bw365.net:2181,zk3.bw365.net:2181
  provider:
    version: 1.0.0
  consumer:
    check: false
    version: 1.0.0

rocketmq:
  namesrvAddr: namesrv1.bw365.net:9876;namesrv2.bw365.net:9876
  consumer:
    group: learn-for-forever-consumer-group
  producer:
    group: learn-for-forever-producer-group
    retryTimes: 3
  order:
    consumer:
      topic: topic_order_detail
      tags: tag_order_settle_ready

app:
  id: learn-for-forever
apollo:
  bootstrap:
    enabled: true

zkAddress: zk1.bw365.net,zk2.bw365.net,zk3.bw365.net
zkPort: 2181

#zookeeperAddress: zk1.bw365.net:2181,zk2.bw365.net:2181,zk3.bw365.net:2181
#
#nameSpace: bw-job
#
#test.value: 22

